# Generated by Django 4.2.4 on 2023-10-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0027_alter_results_result_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='paid',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
