# Generated by Django 4.2.4 on 2024-10-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0029_bankinfo_country_exchangerates_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=9107454756, max_length=255),
        ),
    ]
