# Generated by Django 4.2.4 on 2024-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0033_silauser_alter_temporarytransactions_trans_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silauser',
            old_name='address_alias',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='silauser',
            old_name='identity_alias',
            new_name='street_address_2',
        ),
        migrations.RemoveField(
            model_name='silauser',
            name='crypto_address',
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=6643880128, max_length=255),
        ),
    ]
