# Generated by Django 4.2.4 on 2024-11-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0034_rename_address_alias_silauser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silauser',
            name='street_address_2',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=2504542329, max_length=255),
        ),
    ]
