# Generated by Django 4.2.4 on 2025-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0036_remove_register_address_remove_register_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='register',
            name='lname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='register',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=8050234319, max_length=255),
        ),
    ]
