# Generated by Django 4.2.4 on 2025-04-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0037_register_fname_register_lname_register_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=1383105699, max_length=255),
        ),
    ]
