# Generated by Django 4.2.4 on 2025-04-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0038_alter_temporarytransactions_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silauser',
            name='postal_code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=2656746144, max_length=255),
        ),
    ]
