# Generated by Django 4.2.4 on 2025-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0039_alter_silauser_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=4421739378, max_length=255),
        ),
    ]
