# Generated by Django 4.2.4 on 2025-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_app', '0042_alter_temporarytransactions_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=3858853126, max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=3343122559, max_length=255),
        ),
    ]
